### ISSUE TITLE
job template: default value of not-required argument ist not honored

### ISSUE THREAD

**Issue by rfx77** [sos-berlin/js7#9]
when i add an argument to a job-template which is not required and add a value this value is not honored in the execution of the job. 
i have to provide a value also on the job in the workflow. otherwise i get an error that the argument is not found

My Version is 2.6.0

The problem seems to com from the definition of the env-section ("DSTBASEXLS": "$dstbasexls").
This mapping is copied to the job-instance in the workflow but there is no node-property with this name set.

Error:
`
2023-07-24 11:44:05.862+02:00 [ERROR] [OrderProcessed] id=#2023-07-24#T19184570145-root, pos=0, Job=bericht, Agent(time=2023-07-24 11:43:55.960+02:00), Error (status=failed, reason=disrupted, msg=No such named value: dstbasexls)
`

Job-template:

```
{
  "version": "1.6.0",
  "executable": {
    "TYPE": "ShellScriptExecutable",
    "script": "set\n\n##!include Eis.RunERD \n",
    "env": {
      "ERDNAME": "$erdname",
      "ERDPATH": "$erdpath",
      "DSTBASEXLS": "$dstbasexls"
    },
    "v1Compatible": false
  },
  "skipIfNoAdmissionForOrderDay": false,
  "parallelism": 1,
  "graceTimeout": 1,
  "failOnErrWritten": false,
  "warnOnErrWritten": false,
  "arguments": {
    "erdname": {
      "type": "String",
      "required": true
    },
    "erdpath": {
      "type": "String",
      "required": true
    },
    "dstbasexls": {
      "type": "String",
      "default": "\"testvalue\"",
      "required": false
    }
  },
  "title": "Eis.ExecuteErd"
}
```

Workflow:
```

{
  "version": "1.6.0",
  "timeZone": "Europe/Vienna",
  "instructions": [
    {
      "TYPE": "Execute.Named",
      "jobName": "bericht",
      "defaultArguments": {
        "erdname": "\"monate\"",
        "erdpath": "\"vertrieb\""
      },
      "label": "bericht"
    }
  ],
  "jobs": {
    "bericht": {
      "agentName": "iskdt01",
      "withSubagentClusterIdExpr": false,
      "executable": {
        "TYPE": "ShellScriptExecutable",
        "script": "set\n\n##!include Eis.RunERD \n",
        "env": {
          "ERDNAME": "$erdname",
          "ERDPATH": "$erdpath",
          "DSTBASEXLS": "$dstbasexls"
        },
        "v1Compatible": false
      },
      "skipIfNoAdmissionForOrderDay": false,
      "parallelism": 1,
      "graceTimeout": 1,
      "failOnErrWritten": false,
      "warnOnErrWritten": false,
      "jobTemplate": {
        "name": "Eis.ExecuteErd",
        "hash": "da196c19912c936277d7801b25d07b104376de4712799851de66cd279e4b1145"
      },
      "title": "Eis.ExecuteErd"
    }
  }
}


```

**Comment by sosap** [comment]
When you use an environment variable DSTBASEXLS that is assigned a workflow variable $dstbasexls then you need some source that will declare/set the workflow variable. You have a choice:

1) declare the variable with the Workflow
2) set the variable from a Node Argument
3) set the variable from a Job Resource
4) set the variable dynamically from a predecessor job.

All four sources are out of reach of Job Templates that are focused on single jobs (technically the Job Template can introduce a Job Resource). This means that the source of variables cannot be decided by the Job Template.

The fact that a Job Template's argument is not added to the resulting job is due to the handling of empty values. By default jobs deny use of empty argument values. You can modify this behavior by use of a global setting "allow_empty_arguments", see [JS7 - JOC Cockpit Settings](https://kb.sos-berlin.com/display/JS7/JS7+-+Settings#JS7Settings-joc_settingsJOCCockpitSettings) and below screenshot.

![allow_empty_arguments](https://github.com/sos-berlin/js7/assets/6306352/a6aec83e-37c7-4f7d-a24a-0797e696e8dd)

**Comment by rfx77** [comment]
what use is the default value of a variable in the job-template then for?

**Comment by sosap** [comment]
A Job Template's default value applies to an argument, not to an environment variable.

* Shell jobs make use of environment variables
* JVM jobs (Java, JavaScript, JITL) use arguments. If a default value is provided for a required argument then the value is used to populate the argument, otherwise the user has to specify the argument value.
